### ISSUE TITLE
List item style leaking into header nav

### ISSUE THREAD

**Issue by dannydb** [nprapps/playgrounds2#182]
This bit at line 445 of app.less is causing the issue in the screenshot

``` less
.playground {
    h3 {
        margin: 0 0 11px 0;
        font-size: 18px;
    }
    p, li {
        font-size: 15px;
        line-height: 1.4;
    }
```

![image](https://f.cloud.github.com/assets/419297/664853/a4d69c7a-d78e-11e2-912c-14c1398e2146.png)
